/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaymentTypeDto } from './payment-type-dto';
 /**
 * 
 *
 * @export
 * @interface CheckoutResponseDto
 */
export interface CheckoutResponseDto {

    /**
     * Unique identifier for the checkout session
     *
     * @type {string}
     * @memberof CheckoutResponseDto
     */
    checkoutId: string;

    /**
     * URL for the second step of the checkout process
     *
     * @type {string}
     * @memberof CheckoutResponseDto
     */
    checkoutUrl: string;

    /**
     * Array of available payment types for this checkout
     *
     * @type {Array<PaymentTypeDto>}
     * @memberof CheckoutResponseDto
     */
    paymentTypes: Array<PaymentTypeDto>;
}
