/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePlanDto
 */
export interface CreatePlanDto {

    /**
     * @type {number}
     * @memberof CreatePlanDto
     */
    price: number;

    /**
     * @type {boolean}
     * @memberof CreatePlanDto
     */
    isLifetime: boolean;

    /**
     * @type {number}
     * @memberof CreatePlanDto
     */
    durationDays: number;

    /**
     * @type {string}
     * @memberof CreatePlanDto
     */
    paymentModel: string;
}
