/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePlanDto
 */
export interface CreatePlanDto {

    /**
     * @type {number}
     * @memberof CreatePlanDto
     */
    price: number;

    /**
     * @type {number}
     * @memberof CreatePlanDto
     */
    initialPrice: number;

    /**
     * @type {number}
     * @memberof CreatePlanDto
     */
    durationDays: number;

    /**
     * @type {number}
     * @memberof CreatePlanDto
     */
    freeDays: number;

    /**
     * @type {boolean}
     * @memberof CreatePlanDto
     */
    oncePerUser: boolean;

    /**
     * @type {string}
     * @memberof CreatePlanDto
     */
    paymentModel: CreatePlanDtoPaymentModelEnum;

    /**
     * @type {Array<string>}
     * @memberof CreatePlanDto
     */
    paymentTypes: Array<CreatePlanDtoPaymentTypesEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum CreatePlanDtoPaymentModelEnum {
    ONETIME = 'ONETIME',
    SUBSCRIPTION = 'SUBSCRIPTION',
    LIFETIME = 'LIFETIME'
}
/**
 * @export
 * @enum {string}
 */
export enum CreatePlanDtoPaymentTypesEnum {
    STRIPE = 'STRIPE',
    PAYPAL = 'PAYPAL',
    PAYPALFNF = 'PAYPAL_FNF',
    CRYPTO = 'CRYPTO',
    CASHAPP = 'CASHAPP',
    VENMO = 'VENMO',
    ZELLE = 'ZELLE'
}

