/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Enable2FAResponseDto
 */
export interface Enable2FAResponseDto {

    /**
     * @type {string}
     * @memberof Enable2FAResponseDto
     */
    secret: string;

    /**
     * @type {string}
     * @memberof Enable2FAResponseDto
     */
    totpUri: string;

    /**
     * @type {string}
     * @memberof Enable2FAResponseDto
     */
    qrCodeUrl: string;
}
