/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IntegrationDto
 */
export interface IntegrationDto {

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    type: string;
}
