/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RoleDto } from './role-dto';
 /**
 * 
 *
 * @export
 * @interface IntegrationDto
 */
export interface IntegrationDto {

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    type: IntegrationDtoTypeEnum;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    guildId?: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    guildName?: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    logChannel?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    pastDueRoleId?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    cancellationAction?: IntegrationDtoCancellationActionEnum;

    /**
     * @type {Array<RoleDto>}
     * @memberof IntegrationDto
     */
    discordRoles?: Array<RoleDto>;
}

/**
 * @export
 * @enum {string}
 */
export enum IntegrationDtoTypeEnum {
    DISCORD = 'DISCORD',
    TELEGRAM = 'TELEGRAM'
}
/**
 * @export
 * @enum {string}
 */
export enum IntegrationDtoCancellationActionEnum {
    NONE = 'NONE',
    REMOVEROLE = 'REMOVE_ROLE',
    REMOVEALLROLES = 'REMOVE_ALL_ROLES',
    KICK = 'KICK',
    BAN = 'BAN'
}

