/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductDto } from './product-dto';
 /**
 * 
 *
 * @export
 * @interface MerchantDto
 */
export interface MerchantDto {

    /**
     * @type {string}
     * @memberof MerchantDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof MerchantDto
     */
    slug: string;

    /**
     * @type {string}
     * @memberof MerchantDto
     */
    status: string;

    /**
     * @type {string}
     * @memberof MerchantDto
     */
    motto: string;

    /**
     * @type {string}
     * @memberof MerchantDto
     */
    description: string;

    /**
     * @type {Array<ProductDto>}
     * @memberof MerchantDto
     */
    products: Array<ProductDto>;
}
