/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductDto } from './product-dto';
 /**
 * 
 *
 * @export
 * @interface PaginatedProductResponseDto
 */
export interface PaginatedProductResponseDto {

    /**
     * @type {Array<ProductDto>}
     * @memberof PaginatedProductResponseDto
     */
    data: Array<ProductDto>;

    /**
     * @type {number}
     * @memberof PaginatedProductResponseDto
     */
    total: number;
}
