/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LinkDto } from './link-dto';
 /**
 * 
 *
 * @export
 * @interface PaginatedLinkResponseDto
 */
export interface PaginatedLinkResponseDto {

    /**
     * @type {Array<LinkDto>}
     * @memberof PaginatedLinkResponseDto
     */
    data: Array<LinkDto>;

    /**
     * @type {number}
     * @memberof PaginatedLinkResponseDto
     */
    total: number;
}
