/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrderDto } from './order-dto';
 /**
 * 
 *
 * @export
 * @interface PaginatedOrderResponseDto
 */
export interface PaginatedOrderResponseDto {

    /**
     * @type {Array<OrderDto>}
     * @memberof PaginatedOrderResponseDto
     */
    data: Array<OrderDto>;

    /**
     * @type {number}
     * @memberof PaginatedOrderResponseDto
     */
    total: number;
}
