/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaymentDto
 */
export interface PaymentDto {

    /**
     * @type {string}
     * @memberof PaymentDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof PaymentDto
     */
    orderId: string;

    /**
     * @type {number}
     * @memberof PaymentDto
     */
    amount: number;

    /**
     * @type {string}
     * @memberof PaymentDto
     */
    currency: string;

    /**
     * @type {string}
     * @memberof PaymentDto
     */
    status: string;

    /**
     * @type {string}
     * @memberof PaymentDto
     */
    paymentMethod: string;

    /**
     * @type {Date}
     * @memberof PaymentDto
     */
    paidAt: Date;

    /**
     * @type {Date}
     * @memberof PaymentDto
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof PaymentDto
     */
    updatedAt: Date;
}
