/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PaymentType {
    STRIPE = 'STRIPE',
    PAYPAL = 'PAYPAL',
    PAYPALFNF = 'PAYPAL_FNF',
    CRYPTO = 'CRYPTO',
    CASHAPP = 'CASHAPP',
    VENMO = 'VENMO',
    ZELLE = 'ZELLE'
}

