/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PlanDto
 */
export interface PlanDto {

    /**
     * @type {number}
     * @memberof PlanDto
     */
    price: number;

    /**
     * @type {boolean}
     * @memberof PlanDto
     */
    isLifetime: boolean;

    /**
     * @type {number}
     * @memberof PlanDto
     */
    durationDays: number;

    /**
     * @type {number}
     * @memberof PlanDto
     */
    freeDays: number;

    /**
     * @type {boolean}
     * @memberof PlanDto
     */
    oncePerUser: boolean;

    /**
     * @type {string}
     * @memberof PlanDto
     */
    paymentModel: string;

    /**
     * @type {string}
     * @memberof PlanDto
     */
    id: string;
}
