/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProductDto
 */
export interface ProductDto {

    /**
     * @type {string}
     * @memberof ProductDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof ProductDto
     */
    description?: string;

    /**
     * @type {string}
     * @memberof ProductDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof ProductDto
     */
    status: ProductDtoStatusEnum;

    /**
     * @type {number}
     * @memberof ProductDto
     */
    activeUsers: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ProductDtoStatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DELETED = 'DELETED',
    ARCHIVED = 'ARCHIVED',
    RESTRICTED = 'RESTRICTED'
}

