/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ReviewDto
 */
export interface ReviewDto {

    /**
     * @type {string}
     * @memberof ReviewDto
     */
    content: string;

    /**
     * @type {number}
     * @memberof ReviewDto
     */
    rating: number;

    /**
     * @type {string}
     * @memberof ReviewDto
     */
    userId: string;

    /**
     * @type {string}
     * @memberof ReviewDto
     */
    id: string;
}
