/* tslint:disable */
/* eslint-disable */
/**
 * Rapid Pass API
 * API docs for Rapid Pass
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpsertSocialMediaDto
 */
export interface UpsertSocialMediaDto {

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    website: string;

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    twitter: string;

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    instagram: string;

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    tiktok: string;

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    facebook: string;

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    youtube: string;

    /**
     * @type {string}
     * @memberof UpsertSocialMediaDto
     */
    discord: string;
}
